name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .
        
      - name: Build
        run: go build -v ./...
        
      - name: Test with the Go CLI
        run: go test
        
      - name: Run a one-line script
        run: echo Hello from our workflow template
